[package]
name = "irc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
crossterm = { version = "0.28.1", features = ["event-stream"] }
tokio = { version = "1.40.0", features = ["full"] }
futures = "0.3.30"